# Site settings
name: John Kelly
description: "Entrepreneur | Backend Software Engineer | Engineering Manager | Consultant | Speaker"
url: "http://johnkellycode.com"

github_username:  johnkelly
twitter_username: code_jk
linkedin_username: jkellyj
stack_of_username: 564761
medium_username:  jkelly_br
# blog_url: "/blog"
# email: your-email@example.domain
public_key_url: "https://keybase.io/jkelly"

avatar: yes
avatar_img_path: "https://avatars0.githubusercontent.com/u/709243"

front_img: yes
front_img_path: "imgs/speaking.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
